#!/usr/bin/env python3
"""Export Sangria Galactic Binary truth sources for generated frequency windows.

This is a validation/debugging tool.  It reads a Sangria/LDC HDF5 catalogue,
loads a windows CSV generated by ``make_sangria_windows.py``, and writes the
truth catalogue sources falling in each analysis/core window.  The output is
intended for comparing BayesLISAx fixed-K or model-selection runs to the known
injections.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from sangria_catalog import EXPECTED_COLUMNS, lisa_gb_approx_snr, read_catalogues

TRUTH_FIELDNAMES = (
    "band_id",
    "rank_by_snr",
    "source_id",
    "source_type",
    "source_index",
    "in_core",
    "in_analysis",
    "is_bright",
    "approx_snr",
    "distance_to_core_boundary_hz",
    "distance_to_analysis_boundary_hz",
    "core_f_min",
    "core_f_max",
    "analysis_f_min",
    "analysis_f_max",
    *EXPECTED_COLUMNS,
)

SUMMARY_FIELDNAMES = (
    "band_id",
    "core_f_min",
    "core_f_max",
    "analysis_f_min",
    "analysis_f_max",
    "n_catalog_sources",
    "n_core_sources",
    "n_bright_sources",
    "brightest_source_id",
    "brightest_frequency",
    "brightest_snr",
    "second_brightest_source_id",
    "second_brightest_frequency",
    "second_brightest_snr",
    "brightest_over_second_snr",
    "brightest_minus_second_snr",
    "brightest_distance_to_core_boundary_hz",
)


def _as_1d(values: Any) -> np.ndarray:
    arr = np.asarray(values)
    arr = np.squeeze(arr)
    if arr.ndim == 0:
        arr = arr.reshape(1)
    if arr.ndim > 1:
        arr = arr.reshape(arr.shape[0], -1)[:, 0]
    return arr


def _to_csv_value(value: Any) -> Any:
    if isinstance(value, (np.floating, float)):
        return f"{float(value):.12g}"
    if isinstance(value, (np.integer, int)):
        return int(value)
    if isinstance(value, (np.bool_, bool)):
        return bool(value)
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return value


def catalogue_to_dataframe(h5_path: str) -> pd.DataFrame:
    """Read all configured GB catalogues into one dataframe with stable IDs."""

    frames: list[pd.DataFrame] = []
    for catalogue in read_catalogues(h5_path):
        if catalogue.size == 0:
            continue
        if "Frequency" not in catalogue.data or "Amplitude" not in catalogue.data:
            continue

        cols: dict[str, np.ndarray] = {}
        for name in EXPECTED_COLUMNS:
            if name in catalogue.data:
                vals = _as_1d(catalogue.data[name])
                if len(vals) == catalogue.size:
                    cols[name] = vals

        if "Frequency" not in cols or "Amplitude" not in cols:
            continue

        df = pd.DataFrame(cols)
        df["source_type"] = catalogue.source_type
        df["source_index"] = np.arange(catalogue.size, dtype=int)
        df["source_id"] = [f"{catalogue.source_type}_{idx:08d}" for idx in range(catalogue.size)]
        frames.append(df)

    if not frames:
        raise RuntimeError("No compatible Sangria GB catalogue sources found in the HDF5 file.")

    return pd.concat(frames, ignore_index=True)


def _boundary_distance(freq: np.ndarray, fmin: float, fmax: float) -> np.ndarray:
    return np.minimum(np.abs(freq - fmin), np.abs(fmax - freq))


def export_truth_rows(
    h5_path: str,
    windows_csv: str,
    tobs: float,
    snr_threshold: float | None,
    core_only: bool,
    bright_only: bool,
    top_n: int | None,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    windows = pd.read_csv(windows_csv)
    required = {"band_id", "core_f_min", "core_f_max", "analysis_f_min", "analysis_f_max"}
    missing = required - set(windows.columns)
    if missing:
        raise ValueError(f"Missing required window columns in {windows_csv}: {sorted(missing)}")

    cat = catalogue_to_dataframe(h5_path)
    freq_all = np.asarray(cat["Frequency"], dtype=float)
    amp_all = np.asarray(cat["Amplitude"], dtype=float)
    lat = np.asarray(cat["EclipticLatitude"], dtype=float) if "EclipticLatitude" in cat else None
    inc = np.asarray(cat["Inclination"], dtype=float) if "Inclination" in cat else None
    cat["approx_snr"] = lisa_gb_approx_snr(freq_all, amp_all, tobs, lat, inc)

    truth_rows: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []

    for _, win in windows.iterrows():
        band_id = str(win["band_id"])
        core_min = float(win["core_f_min"])
        core_max = float(win["core_f_max"])
        analysis_min = float(win["analysis_f_min"])
        analysis_max = float(win["analysis_f_max"])

        if core_only:
            mask = (cat["Frequency"] >= core_min) & (cat["Frequency"] < core_max)
        else:
            mask = (cat["Frequency"] >= analysis_min) & (cat["Frequency"] < analysis_max)

        sub = cat.loc[mask].copy()
        sub["in_core"] = (sub["Frequency"] >= core_min) & (sub["Frequency"] < core_max)
        sub["in_analysis"] = (sub["Frequency"] >= analysis_min) & (sub["Frequency"] < analysis_max)
        sub["is_bright"] = True if snr_threshold is None else (sub["approx_snr"] >= snr_threshold)
        sub["distance_to_core_boundary_hz"] = _boundary_distance(
            np.asarray(sub["Frequency"], dtype=float), core_min, core_max
        )
        sub["distance_to_analysis_boundary_hz"] = _boundary_distance(
            np.asarray(sub["Frequency"], dtype=float), analysis_min, analysis_max
        )

        if bright_only:
            sub = sub.loc[sub["is_bright"]].copy()

        sub = sub.sort_values("approx_snr", ascending=False).reset_index(drop=True)
        if top_n is not None:
            sub = sub.head(top_n).copy()

        for rank, row in enumerate(sub.itertuples(index=False), start=1):
            row_dict = row._asdict()
            out: dict[str, Any] = {
                "band_id": band_id,
                "rank_by_snr": rank,
                "source_id": row_dict.get("source_id"),
                "source_type": row_dict.get("source_type"),
                "source_index": row_dict.get("source_index"),
                "in_core": row_dict.get("in_core"),
                "in_analysis": row_dict.get("in_analysis"),
                "is_bright": row_dict.get("is_bright"),
                "approx_snr": row_dict.get("approx_snr"),
                "distance_to_core_boundary_hz": row_dict.get("distance_to_core_boundary_hz"),
                "distance_to_analysis_boundary_hz": row_dict.get("distance_to_analysis_boundary_hz"),
                "core_f_min": core_min,
                "core_f_max": core_max,
                "analysis_f_min": analysis_min,
                "analysis_f_max": analysis_max,
            }
            for name in EXPECTED_COLUMNS:
                out[name] = row_dict.get(name, "")
            truth_rows.append({key: _to_csv_value(out.get(key, "")) for key in TRUTH_FIELDNAMES})

        # Summary is always based on all analysis-window catalogue sources, not top_n-filtered rows.
        analysis_mask = (cat["Frequency"] >= analysis_min) & (cat["Frequency"] < analysis_max)
        analysis_sub = cat.loc[analysis_mask].copy().sort_values("approx_snr", ascending=False).reset_index(drop=True)
        bright_count = 0 if snr_threshold is None else int((analysis_sub["approx_snr"] >= snr_threshold).sum())
        core_count = int(((analysis_sub["Frequency"] >= core_min) & (analysis_sub["Frequency"] < core_max)).sum())

        if len(analysis_sub) > 0:
            first = analysis_sub.iloc[0]
            first_dist = float(_boundary_distance(np.asarray([first["Frequency"]], dtype=float), core_min, core_max)[0])
        else:
            first = None
            first_dist = np.nan
        second = analysis_sub.iloc[1] if len(analysis_sub) > 1 else None

        first_snr = float(first["approx_snr"]) if first is not None else 0.0
        second_snr = float(second["approx_snr"]) if second is not None else 0.0
        ratio = first_snr / second_snr if second_snr > 0.0 else np.inf if first_snr > 0.0 else 0.0
        delta = first_snr - second_snr

        summary = {
            "band_id": band_id,
            "core_f_min": core_min,
            "core_f_max": core_max,
            "analysis_f_min": analysis_min,
            "analysis_f_max": analysis_max,
            "n_catalog_sources": int(len(analysis_sub)),
            "n_core_sources": core_count,
            "n_bright_sources": bright_count,
            "brightest_source_id": first["source_id"] if first is not None else "",
            "brightest_frequency": first["Frequency"] if first is not None else "",
            "brightest_snr": first_snr,
            "second_brightest_source_id": second["source_id"] if second is not None else "",
            "second_brightest_frequency": second["Frequency"] if second is not None else "",
            "second_brightest_snr": second_snr,
            "brightest_over_second_snr": ratio,
            "brightest_minus_second_snr": delta,
            "brightest_distance_to_core_boundary_hz": first_dist,
        }
        summary_rows.append({key: _to_csv_value(summary.get(key, "")) for key in SUMMARY_FIELDNAMES})

    return truth_rows, summary_rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("h5_path", help="Input Sangria/LDC HDF5 file")
    parser.add_argument("--windows-csv", required=True, help="Window CSV from make_sangria_windows.py")
    parser.add_argument("--tobs", type=float, default=31557600.0, help="Observation time [s]")
    parser.add_argument("--snr-threshold", type=float, default=7.0, help="Threshold defining bright truth sources")
    parser.add_argument("--out-csv", required=True, help="Output per-source truth CSV")
    parser.add_argument("--out-summary-csv", default=None, help="Optional per-window summary CSV")
    parser.add_argument("--core-only", action="store_true", help="Export only sources inside the core window, not the guard region")
    parser.add_argument("--bright-only", action="store_true", help="Export only sources with approximate SNR above threshold")
    parser.add_argument("--top-n", type=int, default=None, help="Keep only the N loudest selected sources per window")
    args = parser.parse_args()

    if args.top_n is not None and args.top_n <= 0:
        raise ValueError("--top-n must be positive")

    truth_rows, summary_rows = export_truth_rows(
        args.h5_path,
        args.windows_csv,
        args.tobs,
        args.snr_threshold,
        args.core_only,
        args.bright_only,
        args.top_n,
    )

    out_csv = Path(args.out_csv)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with open(out_csv, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=TRUTH_FIELDNAMES)
        writer.writeheader()
        writer.writerows(truth_rows)
    print(f"Wrote {len(truth_rows)} Sangria truth source rows to {out_csv}")

    if args.out_summary_csv:
        out_summary = Path(args.out_summary_csv)
        out_summary.parent.mkdir(parents=True, exist_ok=True)
        with open(out_summary, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=SUMMARY_FIELDNAMES)
            writer.writeheader()
            writer.writerows(summary_rows)
        print(f"Wrote {len(summary_rows)} Sangria truth summary rows to {out_summary}")


if __name__ == "__main__":
    main()
